### ISSUE TITLE
Migração EF - ORM's

### ISSUE THREAD

**Issue by SandroScheuermann** [Amantes-de-Ford-Ka-Joaninha/Rech-a-Car#62]
- [x] ClienteORM
- [x] ClientePFORM
- [x] ClientePJORM
- [x] CnhORM
- [x] CupomORM
- [x] FuncionarioORM
- [x] RelatorioORM
- [x] SenhaORM
- [x] ServicosORM
- [x] VeiculoORM
- [x] AluguelORM
- [x] ParceiroORM
- [x] CategoriaORM
- [x] MotoristaORM
- [x] AluguelFechadoORM

- [x] Garantir que Funcionario.Senha é transiente e nao sera salvo no banco

**Comment by lucascostaaa** [comment]
VAI TOMA NO SEU CU VASCAINO DESGRAÇADO

Em sex., 8 de out. de 2021 às 13:46, Sandro Müller Scheuermann <
***@***.***> escreveu:
